In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from keras.utils.vis_utils import plot_model
from yellowbrick.classifier import ConfusionMatrix

Using TensorFlow backend.


In [2]:
base = datasets.load_iris()

print("Shape =", base.data.shape)

print("\nFeature Names")
[print(i) for i in base.feature_names]

print("\nTarget Names")
[print(i) for i in base.target_names]

print("\nTarget\n", base.target)

Shape = (150, 4)

Feature Names
sepal length (cm)
sepal width (cm)
petal length (cm)
petal width (cm)

Target Names
setosa
versicolor
virginica

Target
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [3]:
previsores = base.data
classe = base.target

print(previsores.shape, classe.shape)

(150, 4) (150,)


In [4]:
classe_dummy = np_utils.to_categorical(classe) # Transformando as classes de iris em colunas
print(classe_dummy)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [5]:
x_train, x_test, y_train, y_test = train_test_split(previsores, classe_dummy, test_size=0.3, random_state=0)

print("\nDisposição da divisão Treino/Teste\n")

print("X Treino:", x_train.shape[0], "registros x", x_train.shape[1], "variáveis preditoras")
print("Y Treino:", y_train.shape[0], "registros x", y_train.shape[1], "variáveis de resposta\n")

print("X Teste:", x_test.shape[0], "registros x", x_test.shape[1], "variáveis preditoras")
print("Y Teste:", y_test.shape[0], "registros x", y_test.shape[1], "variáveis de resposta\n")


Disposição da divisão Treino/Teste

X Treino: 105 registros x 4 variáveis preditoras
Y Treino: 105 registros x 3 variáveis de resposta

X Teste: 45 registros x 4 variáveis preditoras
Y Teste: 45 registros x 3 variáveis de resposta



In [6]:
modelo = Sequential()
modelo.add(Dense(units=5, input_dim=4)) #input_dim = variáveis preditoras
modelo.add(Dense(units=4))
modelo.add(Dense(units=3, activation="softmax")) #units = classe_dummy | softmax = Mais de duas classes na classificação

W0827 18:17:08.099688 21020 deprecation_wrapper.py:119] From C:\Users\A8061267\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0827 18:17:08.126810 21020 deprecation_wrapper.py:119] From C:\Users\A8061267\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0827 18:17:08.129306 21020 deprecation_wrapper.py:119] From C:\Users\A8061267\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [7]:
modelo.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 5)                 25        
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 24        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 15        
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________


In [8]:
modelo.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"]) 

W0827 18:17:08.199241 21020 deprecation_wrapper.py:119] From C:\Users\A8061267\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0827 18:17:08.234208 21020 deprecation_wrapper.py:119] From C:\Users\A8061267\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [9]:
modelo.fit(x_train, y_train, epochs=1000, validation_data=(x_test, y_test))

W0827 18:17:08.340610 21020 deprecation.py:323] From C:\Users\A8061267\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0827 18:17:08.392061 21020 deprecation_wrapper.py:119] From C:\Users\A8061267\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Train on 105 samples, validate on 45 samples
Epoch 1/1000
105/105 [==============================] - 0s 2ms/step - loss: 1.3674 - acc: 0.3238 - val_loss: 1.3763 - val_acc: 0.3778
Epoch 2/1000
105/105 [==============================] - 0s 95us/step - loss: 1.2327 - acc: 0.3238 - val_loss: 1.2602 - val_acc: 0.4222
Epoch 3/1000
105/105 [==============================] - 0s 81us/step - loss: 1.1117 - acc: 0.4381 - val_loss: 1.1599 - val_acc: 0.5111
Epoch 4/1000
105/105 [==============================] - 0s 128us/step - loss: 1.0080 - acc: 0.6286 - val_loss: 1.0783 - val_acc: 0.5778
Epoch 5/1000
105/105 [==============================] - 0s 76us/step - loss: 0.9274 - acc: 0.6952 - val_loss: 1.0134 - val_acc: 0.5778
Epoch 6/1000
105/105 [==============================] - 0s 119us/step - loss: 0.8653 - acc: 0.6952 - val_loss: 0.9606 - val_acc: 0.6000
Epoch 7/1000
105/105 [==============================] - 0s 90us/step - loss: 0.8141 - acc: 0.6952 - val_loss: 0.9147 - val_acc: 0.6000
Epoch 8/1

In [10]:
previsoes = modelo.predict(x_test)
previsoes

array([[2.1934735e-13, 6.6137800e-06, 9.9999344e-01],
       [3.8070697e-04, 9.9960357e-01, 1.5739284e-05],
       [9.9997413e-01, 2.5843907e-05, 5.6604249e-29],
       [7.3631878e-13, 1.3212033e-04, 9.9986792e-01],
       [9.9956673e-01, 4.3319847e-04, 8.3256703e-24],
       [4.5791696e-17, 4.6835019e-08, 1.0000000e+00],
       [9.9984443e-01, 1.5553531e-04, 4.0155044e-25],
       [3.5323734e-05, 9.9979323e-01, 1.7144953e-04],
       [2.1123458e-05, 9.9946314e-01, 5.1575358e-04],
       [5.2361900e-04, 9.9947220e-01, 4.1753192e-06],
       [1.0423359e-11, 2.9531785e-04, 9.9970466e-01],
       [6.4317726e-05, 9.9983692e-01, 9.8693956e-05],
       [1.2625388e-05, 9.9368906e-01, 6.2982626e-03],
       [2.5993837e-05, 9.9883193e-01, 1.1421436e-03],
       [8.6892378e-06, 9.8016822e-01, 1.9823100e-02],
       [9.9981922e-01, 1.8085334e-04, 3.6200115e-25],
       [1.6962422e-05, 9.9034834e-01, 9.6346904e-03],
       [1.2927967e-05, 9.5036352e-01, 4.9623515e-02],
       [9.9913079e-01, 8.692

In [11]:
previsoes = (previsoes>0.5)
previsoes

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [12]:
y_test_matriz = [np.argmax(i) for i in y_test]
print(np.array(y_test_matriz))

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0]


In [13]:
y_previsao_matriz = [np.argmax(i) for i in previsoes]
print(np.array(y_previsao_matriz))

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2 1 1 2 0 2 0 0]


In [14]:
matriz = confusion_matrix(y_test_matriz, y_previsao_matriz)
matriz

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)